version: "3.8"

services:

  mongo_database:
    image: mongo:5.0
    restart: always
    mem_limit: 512M
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD}
    volumes:
      - mongoData:/data/db

  mongo_express:
    image: mongo-express:0.54.0
    restart: always
    mem_limit: 512M
    ports:
      - 8081:8081
    depends_on:
      - mongo_database
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_database
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=mydb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${LOGIN}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${PASSWORD}

volumes:
  mongoData: