version: "3.8"

services:

  mongo_database:
    image: mongo:5.0
    container_name: mongo_database
    ports:
      - 27017:27017
    deploy:
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure
    healthcheck:
      test: mongo localhost:27017 || exit 1
      interval: 30s
      retries: 3
      start_period: 15s
      timeout: 10s
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD}
    volumes:
      - mongoData:/data/db

  mongo_express:
    image: mongo-express:0.54.0
    container_name: mongo_express
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 8081:8081
    depends_on:
      - mongo_database
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8081 || exit 1
      interval: 30s
      retries: 3
      start_period: 15s
      timeout: 10s
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_database
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=mydb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${LOGIN}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${PASSWORD}

volumes:
  mongoData: